/** Same categories as the AgRaz app service registration form. */
export const SERVICE_CATEGORIES = {
  "Farming Services": [
    "Labour Supply",
    "Harvesting-Manual",
    "Harvesting-Doti",
    "Spraying-Manual",
    "Spraying-Doti",
    "Drone Services",
    "JCB/Hitachi",
    "Tractor",
    "Agri Input Suppliers",
    "Manure Suppliers",
    "Implement Suppliers",
    "Implement Renting",
    "Peeling Services",
    "Peeling Machine",
    "Weeder",
    "Grass/Weed Cutting",
    "Areca Sorting",
    "New Plantation Planning",
    "Irrigation Planning",
    "Drainage Planning",
    "Irrigation Service",
    "Drainage System Service",
    "Electricity Services",
    "Goods Vehicle Service",
    "Dry Leaf Suppliers",
    "Dry Grass Suppliers",
    "Labours",
    "Coconut Harvesting",
    "Coconut Peeling",
    "Soil Suppliers",
    "Soil Work Team",
    "Laterite Supplier",
    "Kaluve Builders",
    "Well Diggers",
    "Areca Pickers",
  ],
  "Animal Husbandry": [
    "Animal Feed",
    "Dry Fodder",
    "Silage",
    "Animal Medicine",
    "Cows and Buffalos",
    "Animal Treatment Ayurvedic",
    "Animal Treatment Allopathy",
    "Accessories",
    "Milking Machine",
    "Inseminators",
    "Doctors",
  ],
  "Passenger Vehicle": ["Car", "Jeep", "Tempo", "Bus", "Bike", "Rickshaw"],
  "Goods Vehicle": ["Pick Up", "Ace", "Jeeto", "Tractor", "Lorry"],
  "JCB/Hitachi": ["JCB", "Hitachi", "Mini Hitachi"],
  Medicine: ["Ayurvedic", "Other Methods"],
  "Other Services": [
    "Electricians",
    "Plumbers",
    "Building Contractors",
    "Engineers",
    "Gavadi Work",
    "POP Work",
    "Solar Services",
    "Welders",
    "Interior Designers",
    "Painters",
    "Foundation Workers",
    "Movers and Packers",
    "Toilet Cleaning",
    "Other Works",
    "Tailoring",
    "Cement Works-Ring/Door Frame Window",
    "Banana Buyers",
    "Togaru/Other buyers",
    "Areca Buyers",
    "Coconut Buyers",
    "Raddi Buyers",
  ],
};

export const MAIN_CATEGORIES = Object.keys(SERVICE_CATEGORIES);
